site = "https://blog.example.com"
base = "/"
outDir = "./dist"
srcDir = "./src"

[output]
type = "static"

[server]
port = 4322
host = "localhost"

[markdown]
syntaxHighlight = "monokai"

[content]
collections = true
contentDir = "./src/content"
